### ISSUE TITLE
error when install from pip

### ISSUE THREAD

**Issue by wankey** [KeepSafe/android-resource-remover#22]
Collecting android-resource-remover
  Using cached android-resource-remover-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\CHENGW~1\AppData\Local\Temp\pip-build-tuk9atu3\android-resource-remover\setup.py", line 15, in <module>
        long_description='\n\n'.join((read('README.md'), read('CHANGELOG'))),
      File "C:\Users\CHENGW~1\AppData\Local\Temp\pip-build-tuk9atu3\android-resource-remover\setup.py", line 9, in read
        return open(os.path.join(os.path.dirname(__file__), f)).read().strip()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 2747: illegal multibyte sequence

**Comment by ca77y** [comment]
what is the file encoding when pip clones a git repo `C:\Users\CHENGW~1\AppData\Local\Temp\pip-build-tuk9atu3\android-resource-remover`. it should be `utf8`
