### ISSUE TITLE
What's the problem when excute comment

### ISSUE THREAD

**Issue by wdysunflower** [KeepSafe/android-resource-remover#24]
do commend(android-resource-remover) with follow error

Traceback (most recent call last):
  File "D:\Python27\Scripts\android-resource-remover-script.py", line 9, in <module>
    load_entry_point('android-resource-remover==0.1.4', 'console_scripts', 'android-resource-remover')()
  File "D:\Python27\lib\site-packages\android_clean_app.py", line 141, in main
    lint_result_path, app_dir, ignore_layouts = run_lint_command()
  File "D:\Python27\lib\site-packages\android_clean_app.py", line 78, in run_lint_command
    call_result = subprocess.call([lint, app_dir, '--xml', lint_result])
  File "D:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "D:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "D:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)

“lint” command success alone

**Comment by wdysunflower** [comment]
what can I do!?

**Comment by ca77y** [comment]
i have no idea what's the problem here and i was not able to reproduce this.
please make sure you have lint in you path. if still facing the problem run lint manually and use `--xml` option to point the resource remover to lint results
