### ISSUE TITLE
Can't able to run

### ISSUE THREAD

**Issue by jayrparro** [KeepSafe/android-resource-remover#30]
I've encountered the error below.
Any idea to fix? Thanks.
```
$ android-resource-remover
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/android-resource-remover", line 9, in <module>
    load_entry_point('android-resource-remover==0.1.5', 'console_scripts', 'android-resource-remover')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/android_clean_app.py", line 141, in main
    lint_result_path, app_dir, ignore_layouts = run_lint_command()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/android_clean_app.py", line 77, in run_lint_command
    call_result = subprocess.call([lint, app_dir, '--xml', lint_result])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by ca77y** [comment]
check if you have lint in your path
