### ISSUE TITLE
UnicodeEncodeError when running

### ISSUE THREAD

**Issue by wankey** [KeepSafe/android-resource-remover#31]
android-resource-remover --xml app/build/outputs/lint-results.xml        
Traceback (most recent call last):
  File "/usr/local/bin/android-resource-remover", line 9, in <module>
    load_entry_point('android-resource-remover==0.1.5', 'console_scripts', 'android-resource-remover')()
  File "build/bdist.macosx-10.11-intel/egg/android_clean_app.py", line 143, in main
    remove_unused_resources(issues, app_dir, ignore_layouts)
  File "build/bdist.macosx-10.11-intel/egg/android_clean_app.py", line 135, in remove_unused_resources
    remove_resource_file(issue, filepath, ignore_layouts)
  File "build/bdist.macosx-10.11-intel/egg/android_clean_app.py", line 107, in remove_resource_file
    print('removing resource: {0}'.format(filepath))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 19-23: ordinal not in range(128)

os: mac
python version: 2.7.10

**Comment by ca77y** [comment]
you have unicode characters in filepath. you can just move to python 3.5 and this should address your problem. right now we are not planning on fixing this issue but i'll add it to our backlog
