### ISSUE TITLE
Execution Error; Seeking Help

### ISSUE THREAD

**Issue by jig08** [KeepSafe/android-resource-remover#36]
After installing (via `sudo pip install android-resource-remover`) successfully, cd-ing into the app directory and executing `android-resource-remover` I receive the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/android-resource-remover", line 9, in <module>
    load_entry_point('android-resource-remover==0.1.5', 'console_scripts', 'android-resource-remover')()
  File "/usr/local/lib/python2.7/dist-packages/android_clean_app.py", line 141, in main
    lint_result_path, app_dir, ignore_layouts = run_lint_command()
  File "/usr/local/lib/python2.7/dist-packages/android_clean_app.py", line 77, in run_lint_command
    call_result = subprocess.call([lint, app_dir, '--xml', lint_result])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

***
Environment :
* Linux Ubuntu 14.04 LTS 
* Python 2.7.6 
* Android Studio 1.3 
* JRE 1.8

**Help Appreciated :)**

**Comment by jig08** [comment]
On trying to set the LINT path i.e on executing `android-resource-remover --lint /home/jigyasa/Android/Sdk/tools/lib/lint.jar` I get the following:
```
Traceback (most recent call last):
  File "/usr/local/bin/android-resource-remover", line 9, in <module>
    load_entry_point('android-resource-remover==0.1.5', 'console_scripts', 'android-resource-remover')()
  File "/usr/local/lib/python2.7/dist-packages/android_clean_app.py", line 141, in main
    lint_result_path, app_dir, ignore_layouts = run_lint_command()
  File "/usr/local/lib/python2.7/dist-packages/android_clean_app.py", line 77, in run_lint_command
    call_result = subprocess.call([lint, app_dir, '--xml', lint_result])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by rohitraj280** [comment]
Hey @jig08 & @philippb ,

After installing (via sudo pip install android-resource-remover) successfully, cd-ing into the app directory and executing android-resource-remover I receive the following error:

android-resource-remover: command not found

Can u help me in dis..?

**Comment by rohitraj280** [comment]
Environment :

Linux Ubuntu 15.10 LTS
Python 2.7.10
Android Studio 1.5.1

Plzz help.. :(

**Comment by jig08** [comment]
@rohitraj280 Seems in your case, the installation wasn't successful.

**Comment by manyata** [comment]
Also getting the same error as @jig08 

Environment :

Mac OS elCapitan 10.11.2
Python 2.7.10
Android Studio 2.0 Preview 4
JRE 1.7

**Comment by jig08** [comment]
@philippb Help appreciated :)

**Comment by manyata** [comment]
@ca77y  can you help us?

**Comment by ca77y** [comment]
hi,

those are installation issues with pip or easy_install. as suggested in #33 you can use easy_install. i'll take a look into the whole installation process soon. For now please make sure the command installs correctly

**Comment by manyata** [comment]
i used easy_install only ..  still getting this issue..
