### ISSUE TITLE
pip install error on Windows: UnicodeDecodeError:

### ISSUE THREAD

**Issue by marco-manza** [KeepSafe/android-resource-remover#38]
pip install android-resource-remover

Collecting android-resource-remover
  Using cached android-resource-remover-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\asm\AppData\Local\Temp\pip-build-oa9d_rfx\android-resource-remover\setup.py", line 15, in <module>
        long_description='\n\n'.join((read('README.md'), read('CHANGELOG'))),
      File "C:\Users\asm\AppData\Local\Temp\pip-build-oa9d_rfx\android-resource-remover\setup.py", line 9, in read
        return open(os.path.join(os.path.dirname(__file__), f)).read().strip()
      File "c:\software\python 3.5.1\lib\encodings\cp1250.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x83 in position 3075: character maps to <undefined>
    
    ----------------------------------------

**Comment by xixigeek** [comment]
I get the same errors。So I fix the line 9 in setup.py like this 
"return open(os.path.join(os.path.dirname(__file__), f),encoding='utf-8').read().strip()".

**Comment by ca77y** [comment]
thanks for reporting. this will be handled in #33
