### ISSUE TITLE
IOError: Error reading file 'build/outputs/lint-results.xml'

### ISSUE THREAD

**Issue by Hesamedin** [KeepSafe/android-resource-remover#40]
Hi,
Unfortunately, I wasn't able to get it into for two days so decided to get some help. 
For some reasons I'm not able to use your suggested command, `./gradlew clean build :lint && android-resource-remover --xml build/outputs/lint-results.xml`. 
- `build` tries to create a release and since I'm work on company project and its credential isn't in build.gradle file so process fails.
- Gradle `:lint` is not in root of your project.

So what I do is I first create a debug .apk in normal way. Second, I run `lint` from Gradle window, My-app/app/verification/lint. So `lint-results.xml` will be created in my `build/output` folder. I run this command in terminal now ` android-resource-remover --xml build/outputs/lint-results.xml`. Then I get following error.

I'm using Android Studio 2.0 Preview 5 on Ubuntu 14.04 LTS. Any suggestion would be appreciated. Thanks.

![screenshot from 2016-01-19 12 23 52](https://cloud.githubusercontent.com/assets/1493510/12429647/b976e24e-bea8-11e5-9a2c-38a99634eb5b.png)

**Comment by ca77y** [comment]
Hi,
the script is unable to find the lint results file so your working directory might be different.
I've added a check to it should print better errors. you can install from github and see if it will work.

**Comment by Hesamedin** [comment]
Thanks @ca77y for quick reply.
I downloaded zip file from GitHub and extract it so I have `android-resource-remover-master` on my desktop. Probably I don't know who to install it but I did this way. Thanks for your time ;)

![screenshot from 2016-01-19 14 01 21](https://cloud.githubusercontent.com/assets/1493510/12431888/4230826e-beb5-11e5-8dc5-23f10edabe8a.png)

**Comment by ca77y** [comment]
`pip install -e git+https://github.com/KeepSafe/android-resource-remover.git#egg=android-resource-remover`

i've just created a virtual env in my android project, installed it with the command above and it worked fine

**Comment by Hesamedin** [comment]
Thanks @ca77y 
I installed virtual env and activate it. But at the end of the process of above command I got error this is my stack-trace. Am I doing something wrong?

```
hesam: passenger-android (v3_unallocation_cleanup) $ source venv/bin/activate
(venv)hesam: passenger-android (v3_unallocation_cleanup) $ pip install -e git+https://github.com/KeepSafe/android-resource-remover.git#egg=android-resource-remover
Obtaining android-resource-remover from git+https://github.com/KeepSafe/android-resource-remover.git#egg=android-resource-remover
  Cloning https://github.com/KeepSafe/android-resource-remover.git to ./venv/src/android-resource-remover
Collecting lxml>=3.3.3 (from android-resource-remover)
/home/hesam/android/projects/grabtaxi/passenger-android/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading lxml-3.5.0.tar.gz (3.8MB)
    100% |████████████████████████████████| 3.8MB 127kB/s 
Building wheels for collected packages: lxml
  Running setup.py bdist_wheel for lxml
  Complete output from command /home/hesam/android/projects/grabtaxi/passenger-android/venv/bin/python -c "import setuptools;__file__='/tmp/pip-build-yC6qLL/lxml/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpFGGhO8pip-wheel-:
  Building lxml version 3.5.0.
  Building without Cython.
  ERROR: /bin/sh: 1: xslt-config: not found
  
  ** make sure the development packages of libxml2 and libxslt are installed **
  
  Using build configuration of libxslt
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/cssselect.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/sax.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/builder.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/__init__.py -> build/lib.linux-x86_64-2.7/lxml
  creating build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-2.7/lxml/includes
  creating build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/defs.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/diff.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/builder.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/clean.py -> build/lib.linux-x86_64-2.7/lxml/html
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-2.7/lxml/isoschematron
  copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-2.7/lxml/includes
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  creating build/temp.linux-x86_64-2.7/src/lxml
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
  src/lxml/lxml.etree.c:85:20: fatal error: Python.h: No such file or directory
   #include "Python.h"
                      ^
  compilation terminated.
  Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  creating tmp
  cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitIPj46T.c -o tmp/xmlXPathInitIPj46T.o
  /tmp/xmlXPathInitIPj46T.c:1:26: fatal error: libxml/xpath.h: No such file or directory
   #include "libxml/xpath.h"
                            ^
  compilation terminated.
  *********************************************************************************
  Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
  *********************************************************************************
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for lxml
Failed to build lxml
Installing collected packages: lxml, android-resource-remover
  Running setup.py install for lxml
    Complete output from command /home/hesam/android/projects/grabtaxi/passenger-android/venv/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-yC6qLL/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-e4z0YF-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/hesam/android/projects/grabtaxi/passenger-android/venv/include/site/python2.7/lxml:
    Building lxml version 3.5.0.
    Building without Cython.
    ERROR: /bin/sh: 1: xslt-config: not found
    
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt
    running install
    running build
    running build_py
    running build_ext
    building 'lxml.etree' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
    src/lxml/lxml.etree.c:85:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    cc -I/usr/include/libxml2 -c /tmp/xmlXPathInithES3_4.c -o tmp/xmlXPathInithES3_4.o
    /tmp/xmlXPathInithES3_4.c:1:26: fatal error: libxml/xpath.h: No such file or directory
     #include "libxml/xpath.h"
                              ^
    compilation terminated.
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/hesam/android/projects/grabtaxi/passenger-android/venv/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-yC6qLL/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-e4z0YF-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/hesam/android/projects/grabtaxi/passenger-android/venv/include/site/python2.7/lxml" failed with error code 1 in /tmp/pip-build-yC6qLL/lxml
/home/hesam/android/projects/grabtaxi/passenger-android/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

**Comment by Hesamedin** [comment]
For those who are super novice, like me and have same issue, please have a look at http://stackoverflow.com/a/5178444/513413 to install `libxml2`.

@ca77y I installed your lib successfully via above command but I've fallen into same report, can you please have a look at this, thanks.

```
(venv)hesam: passenger-android (v3_unallocation_cleanup) $ pip install -e git+https://github.com/KeepSafe/android-resource-remover.git#egg=android-resource-remover
Obtaining android-resource-remover from git+https://github.com/KeepSafe/android-resource-remover.git#egg=android-resource-remover
  Updating ./venv/src/android-resource-remover clone
Collecting lxml>=3.3.3 (from android-resource-remover)
/home/hesam/android/projects/grabtaxi/passenger-android/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached lxml-3.5.0.tar.gz
Building wheels for collected packages: lxml
  Running setup.py bdist_wheel for lxml
  Stored in directory: /home/hesam/.cache/pip/wheels/2d/f6/d6/158b79cc088e551305968e312953c9767855a36f39d4e16054
Successfully built lxml
Installing collected packages: lxml, android-resource-remover
  Running setup.py develop for android-resource-remover
Successfully installed android-resource-remover lxml-3.5.0

(venv)hesam: passenger-android (v3_unallocation_cleanup) $ android-resource-remover --xml build/outputs/lint-results.xml
Traceback (most recent call last):
  File "/usr/local/bin/android-resource-remover", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/android_clean_app.py", line 142, in main
    issues = parse_lint_result(lint_result_path)
  File "/usr/local/lib/python2.7/dist-packages/android_clean_app.py", line 88, in parse_lint_result
    root = etree.parse(lint_result_path).getroot()
  File "lxml.etree.pyx", line 3239, in lxml.etree.parse (src/lxml/lxml.etree.c:69955)
  File "parser.pxi", line 1748, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:102066)
  File "parser.pxi", line 1774, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:102330)
  File "parser.pxi", line 1678, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:101365)
  File "parser.pxi", line 1110, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:96817)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91275)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92461)
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91722)
IOError: Error reading file 'build/outputs/lint-results.xml': failed to load external entity "build/outputs/lint-results.xml"
(venv)hesam: passenger-android (v3_unallocation_cleanup) $ 
```

**Comment by Hesamedin** [comment]
@ca77y Thanks bro, your changed was really helpful to find my `--xml` path was wrong input. So I'm passing absolute path like screenshot. But nothing happens after that.

![01](https://cloud.githubusercontent.com/assets/1493510/12438463/588cd27c-bee4-11e5-97b4-a3e9192373c3.png)

My other question is should I add my `venv` folder to version control or I should add it to `.gitignore`? Thanks

**Comment by ca77y** [comment]
no problem.

it's up to you what to do with it. try stackoverflow if you need advice.
