### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by micstart** [KeepSafe/android-resource-remover#42]
Run the "android-resource-remover" command in ubuntu, it's output error:
Traceback (most recent call last):
  File "/usr/local/bin/android-resource-remover", line 9, in <module>
    load_entry_point('android-resource-remover==0.1.5', 'console_scripts', 'android-resource-remover')()
  File "/usr/local/lib/python2.7/dist-packages/android_clean_app.py", line 141, in main
    lint_result_path, app_dir, ignore_layouts = run_lint_command()
  File "/usr/local/lib/python2.7/dist-packages/android_clean_app.py", line 77, in run_lint_command
    call_result = subprocess.call([lint, app_dir, '--xml', lint_result])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by ca77y** [comment]
do you have lint in your path?

**Comment by micstart** [comment]
not install lint, but has a lint result file : result.xml
I'm use "android-resource-remover" --xml result.xml", But it donothin aftre the command processed.

**Comment by manyata** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/android-resource-remover", line 9, in <module>
    load_entry_point('android-resource-remover==0.1.5', 'console_scripts', 'android-resource-remover')()
  File "/usr/local/lib/python2.7/site-packages/android_clean_app.py", line 141, in main
    lint_result_path, app_dir, ignore_layouts = run_lint_command()
  File "/usr/local/lib/python2.7/site-packages/android_clean_app.py", line 77, in run_lint_command
    call_result = subprocess.call([lint, app_dir, '--xml', lint_result])
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory


same error

**Comment by ca77y** [comment]
you need to have lint in your path or specify it when running the command
