### ISSUE TITLE
Exception: `lint` executable could not be found

### ISSUE THREAD

**Issue by BackPackerDz** [KeepSafe/android-resource-remover#54]
Hi, I have this error when I run " android-resource-remover"  

Traceback (most recent call last):
  File "/usr/local/bin/android-resource-remover", line 9, in <module>
    load_entry_point('android-resource-remover==0.1.7', 'console_scripts', 'android-resource-remover')()
  File "/usr/local/lib/python2.7/dist-packages/android_clean_app.py", line 196, in main
    lint_result_path, app_dir, ignore_layouts = run_lint_command()
  File "/usr/local/lib/python2.7/dist-packages/android_clean_app.py", line 94, in run_lint_command
    '`%s` executable could not be found and path to lint result not specified. See --help' % lint)
Exception: `lint` executable could not be found and path to lint result not specified. See --help

**Comment by BackPackerDz** [comment]
Now when I run  "android-resource-remover --xml build/outputs/lint-results.xml"

Traceback (most recent call last):
  File "/usr/local/bin/android-resource-remover", line 9, in <module>
    load_entry_point('android-resource-remover==0.1.7', 'console_scripts', 'android-resource-remover')()
  File "/usr/local/lib/python2.7/dist-packages/android_clean_app.py", line 199, in main
    issues = parse_lint_result(lint_result_path, manifest_path)
  File "/usr/local/lib/python2.7/dist-packages/android_clean_app.py", line 134, in parse_lint_result
    mainfest_string_refs = get_manifest_string_refs(manifest_path)
  File "/usr/local/lib/python2.7/dist-packages/android_clean_app.py", line 109, in get_manifest_string_refs
    with open(manifest_path, 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/faycal/AndroidStudioProjects/Cook/AndroidManifest.xml'

**Comment by ca77y** [comment]
duplicate #53
